### ISSUE TITLE
Hw finished

### ISSUE THREAD

**Issue by bjur** [jaanos/LVR-2016#1]
We have finished our homework which can be found here: https://github.com/bjur/SAT_solver.git
Have a nice day, B

**Comment by jaanos** [comment]
I've added a link to the latest commit. Please let me know if you change anything before the deadline, so I can update the link.

**Comment by bjur** [comment]
We made a couple fixes, and we apologise for inconvenience.

**Comment by jaanos** [comment]
OK, updated.
