### ISSUE TITLE
Error in tutorial code #1

### ISSUE THREAD

**Issue by pr3mar** [jaanos/LVR-2016#6]
https://github.com/jaanos/LVR/blob/416cda66b49a5d0246116f7d8ab0089b82c1b62c/tutorials/2017/thursday/boolean.py#L115
This should be const()

**Comment by jaanos** [comment]
Fixed by setting

https://github.com/jaanos/LVR/blob/0d7ac0c9ee212ca77d381b85141a7fdb4dd9b893/tutorials/2017/thursday/boolean.py#L114
