### ISSUE TITLE
Error in tutorial code #2

### ISSUE THREAD

**Issue by pr3mar** [jaanos/LVR-2016#7]
https://github.com/jaanos/LVR/blob/c808d4bcad1cbc76f8c7782648abaec974e2d431/tutorials/2017/thursday/boolean.py#L68

Let's say that we have an example of x = boolean.Not(boolean.Variable('x')), in this case, there is an infinite recursion.
The solution would be to add a new elif as follows:
```
elif isinstance(self.x, Variable):
            return self
```

**Comment by jaanos** [comment]
Thanks - I've used your code, so af6a00e is attributed to you.
